# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 12:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('active_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.PositiveIntegerField(default=0)),
                ('vote_up', models.PositiveIntegerField(default=0)),
                ('vote_down', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Vote'),
        ),
    ]
